### ISSUE TITLE
Some Feature request and other

### ISSUE THREAD

**Issue by Niclas-M1** [SpectraSolve/tracker#5]
### Describe the solution you'd like

And as some improvements:
1. after succesfull redeeming, translate it also onto german maybe please and also add the amount, what was on the giftcard
2. maybe upgrade the css for the Buttons in the giftcard dashboard
3. make it possible to edit what is shown in the Profile Dropdown and maybe also add the. option to allocate one or some of the Links into the "Window" Menu in WemX (the Windows-Icon thingy between the bell and the language-picker)
4. and maybe also make it possible to edit, if the Currency should be shows in front or after the Amount

**Comment by SiFuMax09** [comment]
Please make a separate request for everything.
